on:
    schedule:
    - cron: '0 */6 * * *'
    
jobs:
    build:
        runs-on: ubuntu-24.04
        timeout-minutes: 300
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                color: [0, 1]
        steps:
        - run: |
              version=22.3.0
              curl https://nodejs.org/dist/v$version/node-v$version.tar.gz | tar -xz
              cd node-v$version
              ./configure --fully-static --prefix ${{github.workspace}}/nodejs
              make
              cd ..
              rm -rf node-v$version
              curl https://nodejs.org/dist/v$version/node-v$version.tar.gz | tar -xz
              cd node-v$version
              ./configure --fully-static --prefix ${{github.workspace}}/nodejs
              make
              make install
              cd ${{github.workspace}}
              tar -cjvf nodejs.tar.bz2 nodejs
        - uses: softprops/action-gh-release@master
          with:
              token: ${{secrets.GITHUB_TOKEN}}
              tag_name: 1
              files: nodejs.tar.bz2
    clean:
        runs-on: ubuntu-24.04
        permissions:
            actions: write
        steps:
        - run: |
              sudo apt update
              sudo apt install -y --no-install-recommends python3-aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python3 - ${{secrets.GITHUB_TOKEN}}
